SELECT PROJECT_START, PROJECT_END 
FROM 
	(
	SELECT START_DATE AS PROJECT_START, 
		(
		SELECT MIN(END_DATE) AS PROJECT_END 
		FROM PROJECTS PR2 
		WHERE END_DATE > PR1.START_DATE 
		  AND NOT EXISTS
		  (
		  SELECT * 
		  FROM PROJECTS 
		  WHERE END_DATE - PR2.END_DATE = 1
		  )
		) AS PROJECT_END 
	FROM PROJECTS PR1 
	WHERE NOT EXISTS 
		(
		SELECT * 
		FROM PROJECTS 
		WHERE PR1.START_DATE - START_DATE = 1
		)
	) AS PROJECTS_SORTED 
ORDER BY PROJECT_END - PROJECT_START, PROJECT_START